[server]
port = 4444

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723/wd/hub"
status-endpoint = "/status"
#se
configs = [
"1", "{\"browserName\": \"chrome\", \"platformName\": \"android\", \"appium:platformVersion\": \"12\"}",
"1", "{\"browserName\": \"safari\", \"platformName\": \"iOS\", \"appium:platformVersion\": \"12.1\"}"
]